service: cvs-tsk-scheduled-operations

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  tracing:
    lambda: true
    apiGateway: true
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'xray:PutTraceSegments'
            - 'xray:PutTelemetryRecords'
          Resource:
            - '*'

plugins:
  - serverless-dynamodb
  - serverless-offline
  - serverless-plugin-tracing
  - serverless-plugin-typescript

functions:
  cleanupVisits:
    handler: src/handler.handler
    events:
      - cloudwatchEvent:
          event:
            source:
              - 'aws.events'
            detail-type:
              - 'Scheduled Event'
            detail:
              task:
                - 'cleanup'
